### ISSUE TITLE
LibActionButton/LibStub error with ElvUI

### ISSUE THREAD

**Issue by Chorthee** [Choonster-WoW-AddOns/CustomTooltips#2]
Since this weeks updates I've been getting the following error:
---ERROR BEGIN
1x ...rfaceCustomTooltips_LibActionButton\core.lua:1: Cannot find a library instance of "LibActionButton-1.0".
[C]: in function `error'
SharedMedia\libs\LibStub\LibStub.lua:38: in function `LibStub'
...rfaceCustomTooltips_LibActionButton\core.lua:1: in main chunk

Locals:
self = <table> {
 NewLibrary = <function> defined @SharedMedia\libs\LibStub\LibStub.lua:20
 minors = <table> {
 }
 minor = 2
 IterateLibraries = <function> defined @SharedMedia\libs\LibStub\LibStub.lua:46
 GetLibrary = <function> defined @SharedMedia\libs\LibStub\LibStub.lua:36
 libs = <table> {
 }
}
major = "LibActionButton-1.0"
silent = nil
---ERROR END

I unloaded all other addons and only have Custom Tooltip, Custom Tooltip:LibActionButton, BugSack and ElvUI loaded and still get this error.

Thanks.

**Comment by Choonster** [comment]
Fixed by 1a73ae5.

**Comment by Choonster** [comment]
ElvUI has started using a modified version of LibActionButton with a different major version (`"LibActionButton-1.0-ElvUI"`), so there was no `"LibActionButton-1.0"` library.

**Comment by Choonster** [comment]
This is now available as 1.05 on Curse and WoWI.
