### ISSUE TITLE
Another ElvUI issue

### ISSUE THREAD

**Issue by Chorthee** [Choonster-WoW-AddOns/CustomTooltips#3]
Still having ElvUI Issue even with CustomTooltips v1.06.  Following is the error...

-----Begin error
1x ...s_LibActionButton\CustomTooltips_LibActionButton-1.06.lua:1: Cannot find a library instance of "LibActionButton-1.0".
[C]: in function `error'
SharedMedia\libs\LibStub\LibStub.lua:38: in function `LibStub'
...s_LibActionButton\CustomTooltips_LibActionButton-1.06.lua:1: in main chunk

Locals:
self = <table> {
 NewLibrary = <function> defined @SharedMedia\libs\LibStub\LibStub.lua:20
 minors = <table> {
 }
 minor = 2
 IterateLibraries = <function> defined @SharedMedia\libs\LibStub\LibStub.lua:46
 GetLibrary = <function> defined @SharedMedia\libs\LibStub\LibStub.lua:36
 libs = <table> {
 }
}
major = "LibActionButton-1.0"
silent = nil
-----End Error

**Comment by Choonster** [comment]
ElvUI is a separate module to LibActionButton now. Disable **CustomTooltips: LibActionButton** and enable **CustomTooltips: ElvUI**.

**Comment by Chorthee** [comment]
I do not see where to select the "Custom Tooltips:ElvUI" addon in Addon Control Panel.  Please advise.
![wowscrnshot_082715_225024](https://cloud.githubusercontent.com/assets/3709961/9538049/2c4d6e6c-4d0e-11e5-92e6-7e428b7a5ec4.jpg)

**Comment by Choonster** [comment]
Whoops, I just realised I screwed up the packaging for the new modules. I'll fix that now.

**Comment by Choonster** [comment]
Fixed in 0b1ad222b2ab1cd2750cebc1fdf7bb387b39e2f3.

**Comment by Choonster** [comment]
This is fixed in 1.07.
